// AUTO-GENERATED by scripts/gen-known-fields.mjs — DO NOT EDIT BY HAND.
// Per-(channel, kind, type) valid field names extracted from docs/upstream/sing-box/**. Consumed by the
// unknown-field linter (knownFieldsRegistry.ts), unioned with the app's handledFields so neither source's
// gaps over-block. Re-generate with: node scripts/gen-known-fields.mjs

export const DOC_FIELD_NAMES = {
  "stable": {
    "byKind": {
      "inbound": {
        "anytls": [
          "users",
          "padding_scheme",
          "tls"
        ],
        "direct": [
          "network",
          "override_address",
          "override_port"
        ],
        "http": [
          "tls",
          "users",
          "set_system_proxy"
        ],
        "hysteria": [
          "up",
          "up_mbps",
          "obfs",
          "users",
          "recv_window_conn",
          "recv_window_client",
          "max_conn_client",
          "disable_mtu_discovery",
          "tls"
        ],
        "hysteria2": [
          "up_mbps",
          "obfs",
          "users",
          "ignore_client_bandwidth",
          "tls",
          "masquerade",
          "brutal_debug"
        ],
        "mixed": [
          "users",
          "set_system_proxy"
        ],
        "naive": [
          "network",
          "users",
          "quic_congestion_control",
          "tls"
        ],
        "shadowsocks": [
          "network",
          "method",
          "password",
          "managed",
          "multiplex"
        ],
        "shadowtls": [
          "version",
          "password",
          "users",
          "handshake",
          "handshake_for_server_name",
          "strict_mode",
          "wildcard_sni"
        ],
        "socks": [
          "users"
        ],
        "tproxy": [
          "network"
        ],
        "trojan": [
          "users",
          "tls",
          "fallback",
          "fallback_for_alpn",
          "multiplex",
          "transport"
        ],
        "tuic": [
          "users",
          "congestion_control",
          "auth_timeout",
          "zero_rtt_handshake",
          "heartbeat",
          "tls"
        ],
        "tun": [
          "interface_name",
          "address",
          "inet4_address",
          "inet6_address",
          "mtu",
          "gso",
          "auto_route",
          "iproute2_table_index",
          "iproute2_rule_index",
          "auto_redirect",
          "auto_redirect_input_mark",
          "auto_redirect_output_mark",
          "auto_redirect_reset_mark",
          "auto_redirect_nfqueue",
          "auto_redirect_iproute2_fallback_rule_index",
          "exclude_mptcp",
          "loopback_address",
          "strict_route",
          "route_address",
          "inet4_route_address",
          "inet6_route_address",
          "route_exclude_address",
          "inet4_route_exclude_address",
          "inet6_route_exclude_address",
          "route_address_set",
          "route_exclude_address_set",
          "endpoint_independent_nat",
          "udp_timeout",
          "stack",
          "include_interface",
          "exclude_interface",
          "include_uid",
          "include_uid_range",
          "exclude_uid",
          "exclude_uid_range",
          "include_android_user",
          "include_package",
          "exclude_package",
          "platform"
        ],
        "vless": [
          "users",
          "tls",
          "multiplex",
          "transport"
        ],
        "vmess": [
          "users",
          "tls",
          "multiplex",
          "transport"
        ]
      },
      "outbound": {
        "anytls": [
          "server",
          "server_port",
          "password",
          "idle_session_check_interval",
          "idle_session_timeout",
          "min_idle_session",
          "tls"
        ],
        "direct": [
          "override_address",
          "override_port"
        ],
        "http": [
          "server",
          "server_port",
          "username",
          "password",
          "path",
          "headers",
          "tls"
        ],
        "hysteria": [
          "server",
          "server_port",
          "server_ports",
          "hop_interval",
          "up",
          "up_mbps",
          "obfs",
          "auth",
          "auth_str",
          "recv_window_conn",
          "recv_window",
          "disable_mtu_discovery",
          "network",
          "tls"
        ],
        "hysteria2": [
          "server",
          "server_port",
          "server_ports",
          "hop_interval",
          "up_mbps",
          "obfs",
          "password",
          "network",
          "tls",
          "brutal_debug"
        ],
        "naive": [
          "server",
          "server_port",
          "username",
          "password",
          "insecure_concurrency",
          "extra_headers",
          "udp_over_tcp",
          "quic",
          "quic_congestion_control",
          "tls"
        ],
        "selector": [
          "outbounds",
          "default",
          "interrupt_exist_connections"
        ],
        "shadowsocks": [
          "server",
          "server_port",
          "method",
          "password",
          "plugin",
          "plugin_opts",
          "network",
          "udp_over_tcp",
          "multiplex"
        ],
        "shadowtls": [
          "server",
          "server_port",
          "version",
          "password",
          "tls"
        ],
        "socks": [
          "server",
          "server_port",
          "version",
          "username",
          "password",
          "network",
          "udp_over_tcp"
        ],
        "ssh": [
          "server",
          "server_port",
          "user",
          "password",
          "private_key",
          "private_key_path",
          "private_key_passphrase",
          "host_key",
          "host_key_algorithms",
          "client_version"
        ],
        "tor": [
          "executable_path",
          "extra_args",
          "data_directory",
          "torrc"
        ],
        "trojan": [
          "server",
          "server_port",
          "password",
          "network",
          "tls",
          "multiplex",
          "transport"
        ],
        "tuic": [
          "server",
          "server_port",
          "uuid",
          "password",
          "congestion_control",
          "udp_relay_mode",
          "udp_over_stream",
          "network",
          "tls"
        ],
        "urltest": [
          "outbounds",
          "url",
          "interval",
          "tolerance",
          "idle_timeout",
          "interrupt_exist_connections"
        ],
        "vless": [
          "server",
          "server_port",
          "uuid",
          "flow",
          "network",
          "tls",
          "packet_encoding",
          "multiplex",
          "transport"
        ],
        "vmess": [
          "server",
          "server_port",
          "uuid",
          "security",
          "alter_id",
          "global_padding",
          "authenticated_length",
          "network",
          "tls",
          "packet_encoding",
          "multiplex",
          "transport"
        ],
        "wireguard": [
          "server",
          "server_port",
          "system_interface",
          "interface_name",
          "gso",
          "local_address",
          "private_key",
          "peers",
          "peer_public_key",
          "pre_shared_key",
          "reserved",
          "workers",
          "mtu",
          "network"
        ]
      },
      "dns-server": {
        "dhcp": [
          "interface"
        ],
        "fakeip": [
          "inet4_range",
          "inet6_address"
        ],
        "hosts": [
          "path",
          "predefined"
        ],
        "http3": [
          "server",
          "server_port",
          "path",
          "headers",
          "tls"
        ],
        "https": [
          "server",
          "server_port",
          "path",
          "headers",
          "tls"
        ],
        "legacy": [
          "tag",
          "address",
          "address_resolver",
          "address_strategy",
          "strategy",
          "detour",
          "client_subnet"
        ],
        "local": [
          "prefer_go"
        ],
        "quic": [
          "server",
          "server_port",
          "tls"
        ],
        "resolved": [
          "service",
          "accept_default_resolvers"
        ],
        "tailscale": [
          "endpoint",
          "accept_default_resolvers"
        ],
        "tcp": [
          "server",
          "server_port"
        ],
        "tls": [
          "server",
          "server_port",
          "tls"
        ],
        "udp": [
          "server",
          "server_port"
        ]
      },
      "rule-set": {
        "headless-rule": [
          "query_type",
          "network",
          "domain",
          "domain_suffix",
          "domain_keyword",
          "domain_regex",
          "source_ip_cidr",
          "ip_cidr",
          "source_port",
          "source_port_range",
          "port",
          "port_range",
          "process_name",
          "process_path",
          "process_path_regex",
          "package_name",
          "network_type",
          "network_is_expensive",
          "network_is_constrained",
          "network_interface_address",
          "default_interface_address",
          "wifi_ssid",
          "wifi_bssid",
          "invert",
          "type",
          "mode",
          "rules"
        ],
        "source-format": [
          "version",
          "rules"
        ],
        "remote": [
          "type",
          "tag",
          "rules",
          "format",
          "path",
          "url",
          "download_detour",
          "update_interval"
        ],
        "local": [
          "type",
          "tag",
          "rules",
          "format",
          "path",
          "url",
          "download_detour",
          "update_interval"
        ],
        "inline": [
          "type",
          "tag",
          "rules",
          "format",
          "path",
          "url",
          "download_detour",
          "update_interval"
        ]
      },
      "endpoint": {
        "tailscale": [
          "state_directory",
          "auth_key",
          "control_url",
          "ephemeral",
          "hostname",
          "accept_routes",
          "exit_node",
          "exit_node_allow_lan_access",
          "advertise_routes",
          "advertise_exit_node",
          "advertise_tags",
          "relay_server_port",
          "relay_server_static_endpoints",
          "system_interface",
          "system_interface_name",
          "system_interface_mtu",
          "udp_timeout"
        ],
        "wireguard": [
          "system",
          "name",
          "mtu",
          "address",
          "private_key",
          "peers",
          "udp_timeout",
          "workers"
        ]
      },
      "service": {
        "ccm": [
          "credential_path",
          "usages_path",
          "users",
          "headers",
          "detour",
          "tls"
        ],
        "derp": [
          "tls",
          "config_path",
          "verify_client_endpoint",
          "verify_client_url",
          "home",
          "mesh_with",
          "mesh_psk",
          "mesh_psk_file",
          "stun"
        ],
        "ocm": [
          "credential_path",
          "usages_path",
          "users",
          "headers",
          "detour",
          "tls"
        ],
        "resolved": [
          "listen",
          "listen_port"
        ],
        "ssm-api": [
          "servers",
          "cache_path",
          "tls"
        ]
      }
    },
    "shared": {
      "dial": [
        "detour",
        "bind_interface",
        "inet4_bind_address",
        "inet6_bind_address",
        "bind_address_no_port",
        "routing_mark",
        "reuse_addr",
        "netns",
        "connect_timeout",
        "tcp_fast_open",
        "tcp_multi_path",
        "disable_tcp_keep_alive",
        "tcp_keep_alive",
        "tcp_keep_alive_interval",
        "udp_fragment",
        "domain_resolver",
        "network_strategy",
        "network_type",
        "fallback_network_type",
        "fallback_delay",
        "domain_strategy"
      ],
      "listen": [
        "listen",
        "listen_port",
        "bind_interface",
        "routing_mark",
        "reuse_addr",
        "netns",
        "tcp_fast_open",
        "tcp_multi_path",
        "disable_tcp_keep_alive",
        "tcp_keep_alive",
        "tcp_keep_alive_interval",
        "udp_fragment",
        "udp_timeout",
        "detour",
        "sniff",
        "sniff_override_destination",
        "sniff_timeout",
        "domain_strategy",
        "udp_disable_domain_unmapping"
      ],
      "tls": [
        "enabled",
        "disable_sni",
        "server_name",
        "insecure",
        "alpn",
        "min_version",
        "max_version",
        "cipher_suites",
        "curve_preferences",
        "certificate",
        "certificate_path",
        "certificate_public_key_sha256",
        "client_certificate",
        "client_certificate_path",
        "client_key",
        "client_key_path",
        "key",
        "key_path",
        "client_authentication",
        "client_certificate_public_key_sha256",
        "kernel_tx",
        "kernel_rx",
        "utls",
        "pq_signature_schemes_enabled",
        "dynamic_record_sizing_disabled",
        "config",
        "config_path",
        "query_server_name",
        "fragment",
        "fragment_fallback_delay",
        "record_fragment",
        "domain",
        "data_directory",
        "default_server_name",
        "email",
        "provider",
        "disable_http_challenge",
        "disable_tls_alpn_challenge",
        "alternative_http_port",
        "alternative_tls_port",
        "external_account",
        "dns01_challenge",
        "handshake",
        "private_key",
        "public_key",
        "short_id",
        "max_time_difference"
      ],
      "multiplex": [
        "enabled",
        "padding",
        "brutal",
        "protocol",
        "max_connections",
        "min_streams",
        "max_streams"
      ],
      "v2ray-transport": [
        "host",
        "path",
        "method",
        "headers",
        "idle_timeout",
        "ping_timeout",
        "max_early_data",
        "early_data_header_name",
        "service_name",
        "permit_without_stream"
      ],
      "udp-over-tcp": [
        "enabled",
        "version"
      ],
      "tcp-brutal": [
        "enabled",
        "up_mbps"
      ],
      "pre-match": [
        "reject",
        "route",
        "bypass"
      ]
    }
  },
  "testing": {
    "byKind": {
      "inbound": {
        "anytls": [
          "users",
          "padding_scheme",
          "tls"
        ],
        "cloudflared": [
          "token",
          "ha_connections",
          "protocol",
          "post_quantum",
          "edge_ip_version",
          "datagram_version",
          "grace_period",
          "region",
          "control_dialer",
          "tunnel_dialer"
        ],
        "direct": [
          "network",
          "override_address",
          "override_port"
        ],
        "http": [
          "tls",
          "users",
          "set_system_proxy"
        ],
        "hysteria": [
          "up",
          "up_mbps",
          "obfs",
          "users",
          "tls",
          "recv_window_conn",
          "recv_window_client",
          "max_conn_client",
          "disable_mtu_discovery"
        ],
        "hysteria2": [
          "up_mbps",
          "obfs",
          "users",
          "ignore_client_bandwidth",
          "tls",
          "masquerade",
          "bbr_profile",
          "brutal_debug",
          "realm"
        ],
        "mixed": [
          "users",
          "set_system_proxy"
        ],
        "naive": [
          "network",
          "users",
          "quic_congestion_control",
          "tls"
        ],
        "shadowsocks": [
          "network",
          "method",
          "password",
          "managed",
          "multiplex"
        ],
        "shadowtls": [
          "version",
          "password",
          "users",
          "handshake",
          "handshake_for_server_name",
          "strict_mode",
          "wildcard_sni"
        ],
        "socks": [
          "users"
        ],
        "tproxy": [
          "network"
        ],
        "trojan": [
          "users",
          "tls",
          "fallback",
          "fallback_for_alpn",
          "multiplex",
          "transport"
        ],
        "tuic": [
          "users",
          "congestion_control",
          "auth_timeout",
          "zero_rtt_handshake",
          "heartbeat",
          "tls"
        ],
        "tun": [
          "interface_name",
          "address",
          "inet4_address",
          "inet6_address",
          "mtu",
          "dns_mode",
          "dns_address",
          "gso",
          "auto_route",
          "iproute2_table_index",
          "iproute2_rule_index",
          "auto_redirect",
          "auto_redirect_input_mark",
          "auto_redirect_output_mark",
          "auto_redirect_reset_mark",
          "auto_redirect_nfqueue",
          "auto_redirect_iproute2_fallback_rule_index",
          "exclude_mptcp",
          "loopback_address",
          "strict_route",
          "route_address",
          "inet4_route_address",
          "inet6_route_address",
          "route_exclude_address",
          "inet4_route_exclude_address",
          "inet6_route_exclude_address",
          "route_address_set",
          "route_exclude_address_set",
          "endpoint_independent_nat",
          "udp_timeout",
          "stack",
          "include_interface",
          "exclude_interface",
          "include_uid",
          "include_uid_range",
          "exclude_uid",
          "exclude_uid_range",
          "include_android_user",
          "include_package",
          "exclude_package",
          "include_mac_address",
          "exclude_mac_address",
          "platform"
        ],
        "vless": [
          "users",
          "tls",
          "multiplex",
          "transport"
        ],
        "vmess": [
          "users",
          "tls",
          "multiplex",
          "transport"
        ]
      },
      "outbound": {
        "anytls": [
          "server",
          "server_port",
          "password",
          "idle_session_check_interval",
          "idle_session_timeout",
          "min_idle_session",
          "tls"
        ],
        "direct": [
          "override_address",
          "override_port"
        ],
        "http": [
          "server",
          "server_port",
          "username",
          "password",
          "path",
          "headers",
          "tls"
        ],
        "hysteria": [
          "server",
          "server_port",
          "server_ports",
          "hop_interval",
          "up",
          "up_mbps",
          "obfs",
          "auth",
          "auth_str",
          "network",
          "tls",
          "recv_window_conn",
          "recv_window",
          "disable_mtu_discovery"
        ],
        "hysteria2": [
          "server",
          "server_port",
          "server_ports",
          "hop_interval",
          "hop_interval_max",
          "up_mbps",
          "obfs",
          "password",
          "network",
          "tls",
          "bbr_profile",
          "brutal_debug",
          "realm"
        ],
        "naive": [
          "server",
          "server_port",
          "username",
          "password",
          "insecure_concurrency",
          "extra_headers",
          "udp_over_tcp",
          "quic",
          "quic_congestion_control",
          "tls"
        ],
        "selector": [
          "outbounds",
          "default",
          "interrupt_exist_connections"
        ],
        "shadowsocks": [
          "server",
          "server_port",
          "method",
          "password",
          "plugin",
          "plugin_opts",
          "network",
          "udp_over_tcp",
          "multiplex"
        ],
        "shadowtls": [
          "server",
          "server_port",
          "version",
          "password",
          "tls"
        ],
        "socks": [
          "server",
          "server_port",
          "version",
          "username",
          "password",
          "network",
          "udp_over_tcp"
        ],
        "ssh": [
          "server",
          "server_port",
          "user",
          "password",
          "private_key",
          "private_key_path",
          "private_key_passphrase",
          "host_key",
          "host_key_algorithms",
          "client_version",
          "cipher",
          "mac",
          "kex_algorithm"
        ],
        "tor": [
          "executable_path",
          "extra_args",
          "data_directory",
          "torrc"
        ],
        "trojan": [
          "server",
          "server_port",
          "password",
          "network",
          "tls",
          "multiplex",
          "transport"
        ],
        "tuic": [
          "server",
          "server_port",
          "uuid",
          "password",
          "congestion_control",
          "udp_relay_mode",
          "udp_over_stream",
          "network",
          "tls"
        ],
        "urltest": [
          "outbounds",
          "url",
          "interval",
          "tolerance",
          "idle_timeout",
          "interrupt_exist_connections"
        ],
        "vless": [
          "server",
          "server_port",
          "uuid",
          "flow",
          "network",
          "tls",
          "packet_encoding",
          "multiplex",
          "transport"
        ],
        "vmess": [
          "server",
          "server_port",
          "uuid",
          "security",
          "alter_id",
          "global_padding",
          "authenticated_length",
          "network",
          "tls",
          "packet_encoding",
          "multiplex",
          "transport"
        ],
        "wireguard": [
          "server",
          "server_port",
          "system_interface",
          "interface_name",
          "gso",
          "local_address",
          "private_key",
          "peers",
          "peer_public_key",
          "pre_shared_key",
          "reserved",
          "workers",
          "mtu",
          "network"
        ]
      },
      "dns-server": {
        "dhcp": [
          "interface"
        ],
        "fakeip": [
          "inet4_range",
          "inet6_address"
        ],
        "hosts": [
          "path",
          "predefined"
        ],
        "http3": [
          "server",
          "server_port",
          "path",
          "headers",
          "tls"
        ],
        "https": [
          "server",
          "server_port",
          "path",
          "headers",
          "tls"
        ],
        "legacy": [
          "tag",
          "address",
          "address_resolver",
          "address_strategy",
          "strategy",
          "detour",
          "client_subnet"
        ],
        "local": [
          "prefer_go",
          "neighbor_domain"
        ],
        "mdns": [
          "interface"
        ],
        "quic": [
          "server",
          "server_port",
          "tls"
        ],
        "resolved": [
          "service",
          "accept_default_resolvers"
        ],
        "tailscale": [
          "endpoint",
          "accept_default_resolvers",
          "accept_search_domain"
        ],
        "tcp": [
          "server",
          "server_port"
        ],
        "tls": [
          "server",
          "server_port",
          "tls"
        ],
        "udp": [
          "server",
          "server_port"
        ]
      },
      "rule-set": {
        "headless-rule": [
          "query_type",
          "network",
          "domain",
          "domain_suffix",
          "domain_keyword",
          "domain_regex",
          "source_ip_cidr",
          "ip_cidr",
          "source_port",
          "source_port_range",
          "port",
          "port_range",
          "process_name",
          "process_path",
          "process_path_regex",
          "package_name",
          "package_name_regex",
          "network_type",
          "network_is_expensive",
          "network_is_constrained",
          "network_interface_address",
          "default_interface_address",
          "wifi_ssid",
          "wifi_bssid",
          "invert",
          "type",
          "mode",
          "rules"
        ],
        "source-format": [
          "version",
          "rules"
        ],
        "remote": [
          "type",
          "tag",
          "rules",
          "format",
          "path",
          "url",
          "http_client",
          "update_interval",
          "download_detour"
        ],
        "local": [
          "type",
          "tag",
          "rules",
          "format",
          "path",
          "url",
          "http_client",
          "update_interval",
          "download_detour"
        ],
        "inline": [
          "type",
          "tag",
          "rules",
          "format",
          "path",
          "url",
          "http_client",
          "update_interval",
          "download_detour"
        ]
      },
      "endpoint": {
        "tailscale": [
          "state_directory",
          "auth_key",
          "control_url",
          "ephemeral",
          "hostname",
          "accept_routes",
          "exit_node",
          "exit_node_allow_lan_access",
          "advertise_routes",
          "advertise_exit_node",
          "advertise_tags",
          "relay_server_port",
          "relay_server_static_endpoints",
          "system_interface",
          "system_interface_name",
          "system_interface_mtu",
          "udp_timeout"
        ],
        "wireguard": [
          "system",
          "name",
          "mtu",
          "address",
          "private_key",
          "peers",
          "udp_timeout",
          "workers"
        ]
      },
      "service": {
        "ccm": [
          "credential_path",
          "usages_path",
          "users",
          "headers",
          "detour",
          "tls"
        ],
        "derp": [
          "tls",
          "config_path",
          "verify_client_endpoint",
          "verify_client_url",
          "home",
          "mesh_with",
          "mesh_psk",
          "mesh_psk_file",
          "stun"
        ],
        "hysteria-realm": [
          "tls",
          "users"
        ],
        "ocm": [
          "credential_path",
          "usages_path",
          "users",
          "headers",
          "detour",
          "tls"
        ],
        "resolved": [
          "listen",
          "listen_port"
        ],
        "ssm-api": [
          "servers",
          "cache_path",
          "tls"
        ]
      }
    },
    "shared": {
      "dial": [
        "detour",
        "bind_interface",
        "inet4_bind_address",
        "inet6_bind_address",
        "bind_address_no_port",
        "routing_mark",
        "reuse_addr",
        "netns",
        "connect_timeout",
        "tcp_fast_open",
        "tcp_multi_path",
        "disable_tcp_keep_alive",
        "tcp_keep_alive",
        "tcp_keep_alive_interval",
        "udp_fragment",
        "domain_resolver",
        "network_strategy",
        "network_type",
        "fallback_network_type",
        "fallback_delay",
        "domain_strategy"
      ],
      "listen": [
        "listen",
        "listen_port",
        "bind_interface",
        "routing_mark",
        "reuse_addr",
        "netns",
        "tcp_fast_open",
        "tcp_multi_path",
        "disable_tcp_keep_alive",
        "tcp_keep_alive",
        "tcp_keep_alive_interval",
        "udp_fragment",
        "udp_timeout",
        "detour",
        "sniff",
        "sniff_override_destination",
        "sniff_timeout",
        "domain_strategy",
        "udp_disable_domain_unmapping"
      ],
      "tls": [
        "enabled",
        "engine",
        "disable_sni",
        "server_name",
        "insecure",
        "alpn",
        "min_version",
        "max_version",
        "cipher_suites",
        "curve_preferences",
        "certificate",
        "certificate_path",
        "certificate_public_key_sha256",
        "client_certificate",
        "client_certificate_path",
        "client_key",
        "client_key_path",
        "key",
        "key_path",
        "client_authentication",
        "client_certificate_public_key_sha256",
        "kernel_tx",
        "kernel_rx",
        "handshake_timeout",
        "certificate_provider",
        "utls",
        "pq_signature_schemes_enabled",
        "dynamic_record_sizing_disabled",
        "config",
        "config_path",
        "query_server_name",
        "fragment",
        "fragment_fallback_delay",
        "record_fragment",
        "spoof",
        "spoof_method",
        "domain",
        "data_directory",
        "default_server_name",
        "email",
        "provider",
        "disable_http_challenge",
        "disable_tls_alpn_challenge",
        "alternative_http_port",
        "alternative_tls_port",
        "external_account",
        "dns01_challenge",
        "handshake",
        "private_key",
        "public_key",
        "short_id",
        "max_time_difference"
      ],
      "http-client": [
        "engine",
        "version",
        "disable_version_fallback",
        "headers"
      ],
      "http2": [
        "idle_timeout",
        "keep_alive_period",
        "stream_receive_window",
        "connection_receive_window",
        "max_concurrent_streams"
      ],
      "quic": [
        "initial_packet_size",
        "disable_path_mtu_discovery"
      ],
      "multiplex": [
        "enabled",
        "padding",
        "brutal",
        "protocol",
        "max_connections",
        "min_streams",
        "max_streams"
      ],
      "v2ray-transport": [
        "host",
        "path",
        "method",
        "headers",
        "idle_timeout",
        "ping_timeout",
        "max_early_data",
        "early_data_header_name",
        "service_name",
        "permit_without_stream"
      ],
      "udp-over-tcp": [
        "enabled",
        "version"
      ],
      "tcp-brutal": [
        "enabled",
        "up_mbps"
      ],
      "dns01_challenge": [
        "ttl",
        "propagation_delay",
        "propagation_timeout",
        "resolvers",
        "override_domain",
        "provider"
      ],
      "pre-match": [
        "reject",
        "route",
        "bypass"
      ]
    }
  }
} as const;
