#!/usr/bin/env node
// scripts/claude-review/submit.mjs
// Unattended "submit": push current branch → ensure PR exists → run Claude review →
// open a review issue linked to the PR. Companion to run.mjs / pre-push hook.

import { execFileSync, spawnSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const RUN_MJS = resolve(__dirname, "run.mjs");
const ISSUE_BODY_REVIEW_LIMIT = 55_000;

function truncateReviewOutput(reviewOutput) {
  const review = reviewOutput.trim();
  if (review.length <= ISSUE_BODY_REVIEW_LIMIT) return review;
  const omitted = review.length - ISSUE_BODY_REVIEW_LIMIT;
  return [
    review.slice(0, ISSUE_BODY_REVIEW_LIMIT),
    "",
    `[review output truncated: ${omitted} character(s) omitted]`,
  ].join("\n");
}

export function formatIssueBody({ reviewOutput, prNumber, prUrl, headSha, branchName }) {
  const review = truncateReviewOutput(reviewOutput);
  return [
    `Automated Claude pre-push review for **PR #${prNumber}** (\`${branchName}\` @ \`${headSha.slice(0, 8)}\`).`,
    ``,
    `> Source PR: ${prUrl}`,
    ``,
    `---`,
    ``,
    `## Review output`,
    ``,
    review || "(no review output — Claude likely fail-opened; check pre-push stderr or rerun `node scripts/claude-review/run.mjs <range>`)",
    ``,
    `---`,
    ``,
    `🤖 Generated by \`scripts/claude-review/submit.mjs\``,
  ].join("\n");
}

function git(args) {
  return execFileSync("git", args, { encoding: "utf8" }).trim();
}

function trySpawn(cmd, args, options = {}) {
  return spawnSync(cmd, args, { encoding: "utf8", ...options });
}

export function existingReviewIssueUrl(prNumber) {
  const issue = trySpawn("gh", [
    "issue",
    "list",
    "--state",
    "all",
    "--search",
    `"Review of PR #${prNumber}" in:title`,
    "--json",
    "url",
  ]);
  if (issue.status !== 0) return null;
  try {
    const issues = JSON.parse(issue.stdout);
    return typeof issues[0]?.url === "string" ? issues[0].url : null;
  } catch {
    return null;
  }
}

async function main(argv) {
  const dryRun = argv.includes("--dry-run");
  const baseRef = "origin/main";

  const branch = git(["symbolic-ref", "--short", "HEAD"]);
  if (branch === "main" || branch === "master") {
    process.stderr.write(`submit-pr: refusing to submit from ${branch}\n`);
    return 1;
  }
  const headSha = git(["rev-parse", "HEAD"]);
  process.stderr.write(`submit-pr: branch=${branch} head=${headSha.slice(0, 8)}\n`);

  if (dryRun) {
    process.stderr.write(`submit-pr: [dry-run] would: SBC_SKIP_CLAUDE_REVIEW=1 git push -u origin ${branch}\n`);
  } else {
    process.stderr.write("submit-pr: pushing (skipping pre-push review; submit will run review once)...\n");
    const push = trySpawn("git", ["push", "-u", "origin", branch], {
      stdio: "inherit",
      env: { ...process.env, SBC_SKIP_CLAUDE_REVIEW: "1" },
    });
    if (push.status !== 0) {
      process.stderr.write(`submit-pr: git push failed (exit ${push.status})\n`);
      return 1;
    }
  }

  let prNumber;
  let prUrl;
  let prTitle;
  const view = trySpawn("gh", ["pr", "view", "--json", "number,title,url"]);
  if (view.status === 0) {
    const pr = JSON.parse(view.stdout);
    prNumber = pr.number;
    prTitle = pr.title;
    prUrl = pr.url;
    process.stderr.write(`submit-pr: found existing PR #${prNumber}: ${prTitle}\n`);
  } else if (dryRun) {
    process.stderr.write("submit-pr: [dry-run] would: gh pr create --fill --base main\n");
    prNumber = 0;
    prTitle = "(dry-run)";
    prUrl = "(dry-run URL)";
  } else {
    process.stderr.write("submit-pr: no PR for current branch; creating via gh pr create --fill\n");
    const create = trySpawn("gh", ["pr", "create", "--fill", "--base", "main"]);
    if (create.status !== 0) {
      process.stderr.write(`submit-pr: gh pr create failed:\n${create.stderr}\n`);
      return 1;
    }
    prUrl = create.stdout.trim().split(/\r?\n/).pop();
    const m = prUrl?.match(/\/pull\/(\d+)/);
    if (!prUrl || !m) {
      process.stderr.write(`submit-pr: cannot parse PR number from URL: ${prUrl}\n`);
      return 1;
    }
    prNumber = parseInt(m[1], 10);
    const titleR = trySpawn("gh", ["pr", "view", String(prNumber), "--json", "title", "-q", ".title"]);
    prTitle = titleR.status === 0 ? titleR.stdout.trim() : "(unknown title)";
    process.stderr.write(`submit-pr: opened PR #${prNumber}: ${prTitle}\n`);
  }

  const base = git(["merge-base", "HEAD", baseRef]);
  const range = `${base}..${headSha}`;
  process.stderr.write(`submit-pr: running review on ${range}\n`);

  let reviewOutput = "";
  if (dryRun) {
    process.stderr.write(`submit-pr: [dry-run] would: node ${RUN_MJS} ${range}\n`);
    reviewOutput = "(dry-run: review skipped)";
  } else {
    const reviewR = trySpawn("node", [RUN_MJS, range]);
    reviewOutput = (reviewR.stdout || "") + (reviewR.stderr || "");
    process.stderr.write(reviewOutput);
    if (reviewR.status !== 0) {
      process.stderr.write(`submit-pr: review exited ${reviewR.status} (blocking findings present; issue will still be opened)\n`);
    }
  }

  const issueTitle = `Review of PR #${prNumber}: ${prTitle}`;
  const issueBody = formatIssueBody({ reviewOutput, prNumber, prUrl, headSha, branchName: branch });

  let issueUrl;
  if (dryRun) {
    process.stderr.write(`submit-pr: [dry-run] would: gh issue create --title "${issueTitle}"\n`);
    issueUrl = "(dry-run issue URL)";
  } else {
    const existingIssueUrl = existingReviewIssueUrl(prNumber);
    if (existingIssueUrl) {
      process.stderr.write(`submit-pr: review issue already exists: ${existingIssueUrl}\n`);
      process.stdout.write(`PR:    ${prUrl}\n`);
      process.stdout.write(`Issue: ${existingIssueUrl}\n`);
      return 0;
    }
    process.stderr.write("submit-pr: opening review issue...\n");
    const issueR = trySpawn("gh", ["issue", "create", "--title", issueTitle, "--body", issueBody]);
    if (issueR.status !== 0) {
      process.stderr.write(`submit-pr: gh issue create failed:\n${issueR.stderr}\n`);
      return 1;
    }
    issueUrl = issueR.stdout.trim().split(/\r?\n/).pop();

    const comment = trySpawn("gh", [
      "pr",
      "comment",
      String(prNumber),
      "--body",
      `Automated Claude review opened: ${issueUrl}`,
    ]);
    if (comment.status !== 0) {
      process.stderr.write(`submit-pr: gh pr comment failed (non-fatal):\n${comment.stderr}\n`);
    }
  }

  process.stdout.write(`PR:    ${prUrl}\n`);
  process.stdout.write(`Issue: ${issueUrl}\n`);
  return 0;
}

const invokedDirect =
  process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (invokedDirect) {
  main(process.argv.slice(2))
    .then((code) => process.exit(code))
    .catch((err) => {
      process.stderr.write(`submit-pr: unexpected error: ${err.message}\n`);
      process.exit(1);
    });
}
